export const FETCH_PROMPT_PENDING = 'FETCH_PROMPT_PENDING';
export const FETCH_PROMPT_SUCCESS = 'FETCH_PROMPT_SUCCESS';
export const FETCH_PROMPT_FAILED = 'FETCH_PROMPT_FAILED';
export const ADD_PROMPT = 'ADD_PROMPT';
export const STAR_PROMPT = 'STAR_PROMPT';
export const DELETE_PROMPT = 'DELETE_PROMPT';
export const SELECT_GAME_MODE = 'SELECT_GAME_MODE';
export const FETCH_PROMPTS_HISTORY = 'FETCH_PROMPTS_HISTORY';
